### ISSUE TITLE
why do we need a force update?

### ISSUE THREAD

**Issue by sibelius** [CharlesStover/use-react-router#12] opened 2019-04-15 22:06 UTC

**Comment by quisido** [comment] 2019-04-15 22:08
This is a duplicate of #11. The reason for including it is discussed there (to bypass render blocking), but this may already update regardless of manually forcing it.

I'm fine with removing the force update, but I'd want it unit tested beforehand to verify.

**Closed as completed by quisido** 2019-04-15 22:08 UTC
Labels: duplicate
